# Generated by Django 6.0.2 on 2026-02-10 03:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubrun',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='githubrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubrun',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='githubrun',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='githubrun',
            name='filename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='filename'),
        ),
        migrations.AddField(
            model_name='githubrun',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='status',
            field=models.CharField(max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='githubrun',
            name='uuid',
            field=models.CharField(max_length=100, unique=True, verbose_name='uuid'),
        ),
    ]
